# syntax=docker/dockerfile:1
FROM node:23.11-alpine

# set up environment
ENV DIR=/mirador
ENV TERM=linux
SHELL ["/bin/bash", "-c"]

WORKDIR $DIR
COPY .. .
# for debug: install `iproute2` which provides CLI `ss` to monitor active ports
RUN apt update && apt install iproute2 -y
RUN npm i -g

CMD npm run start